version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - revive
    - gosec
    - noctx
    - bodyclose

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/Xwudao/go-timer

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning

  gosec:
    excludes:
      - G204
      - G304
      - G301

issues:
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck
